### ISSUE TITLE
[PE-D][Tester C] Invalid Email values throws IllegalArgumentException 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T11-1/tp#96]
When creating a new person with an invalid email, the IllegalArgumentException is not handled by the application. This results in error messages in the terminal, but no response shown in the application. 

For example:

`person new n/adsfasdf p/1234097 e/31102412457 a/asdfaldf`
Entering this command results in no feedback to the user.

![image.png](https://raw.githubusercontent.com/misterpuffin/ped/main/files/1e0d3151-b6bc-45f1-a778-04ddbbc80e08.png)

If we check the terminal, it shows
``` Caused by: java.lang.IllegalArgumentException: Emails should be of the format local-part@domain and adhere to the following constraints:
1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-). The local-part may not start or end with any special characters.
2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
The domain name must:
    - end with a domain label at least 2 characters long
    - have each domain label start and end with alphanumeric characters
    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.
        at seedu.address.commons.util.AppUtil.checkArgument(AppUtil.java:39)
        at seedu.address.model.attribute.Email.<init>(Email.java:43)
        at seedu.address.logic.parser.persons.AddCommandParser.lambda$parse$2(AddCommandParser.java:59)
        at java.base/java.util.Optional.map(Optional.java:265)
        at seedu.address.logic.parser.persons.AddCommandParser.parse(AddCommandParser.java:59)
        at seedu.address.logic.parser.persons.PersonCommandParser.parse(PersonCommandParser.java:53)
        at seedu.address.logic.parser.AddressBookParser.lambda$static$16(AddressBookParser.java:86)
        at seedu.address.logic.parser.AddressBookParser.parseCommand(AddressBookParser.java:180)
        at seedu.address.logic.LogicManager.execute(LogicManager.java:49)
        at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:204)
        at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:46)
        ... 56 more
```

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: misterpuffin/ped#3

**Comment by Eclipse-Dominator** [comment]
This issue will be addressed by #153
